# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 962340d47e3cd835ae26e2cc21be962088ed460cacea674ee9d66467058518a2fd8586ece5eb785172415dfec7c97a68516ad294f4e9cbd404655521b12aa842

test:
  secret_key_base: 6b929c4514c8e518d1381437bfa274afb89fb0b4ea1133bd4c60fa2ccd2a9117272c07ad8f7ac26445476fac59873dc03e8f2997eb07f7f4932f55f0419959fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
